# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-log4qtdemo

# >> macros
%define __provides_exclude_from ^%{_datadir}/.*$
%define __requires_exclude ^liblog4qt.*$
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Log4Qt demo
Version:    1.0
Release:    3
Group:      Qt/Qt
License:    Public domain
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-log4qtdemo.yaml
Requires:   libsailfishapp
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(sailfishapp)
BuildRequires:  desktop-file-utils

%description
Log4Qt logging library usage demo. Created for Sailfish OS, but same approach can be used for all the other platforms as well

%package test
Summary:    Tests for the Log4Qt demo app
Group:      Qt/Qt
Requires:   %{name} = %{version}-%{release}
Requires:   qt5-qtdeclarative-import-qttest
BuildRequires:  pkgconfig(Qt5QuickTest)

%description test
Tests package for the Log4Qt demo app

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%defattr(0644,root,root,0755)
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
%{_datadir}/applications/%{name}.desktop
%{_datadir}/%{name}/qml
%{_datadir}/%{name}/log4qt.conf
%attr(0755,-,-) %{_bindir}/%{name}
%{_datadir}/%{name}/lib
# >> files
# << files

%files test
%defattr(-,root,root,-)
%{_bindir}/tst-harbour-log4qtdemo-cppTests
%{_bindir}/tst-harbour-log4qtdemo-qmlTests
%{_datadir}/tst-harbour-log4qtdemo-qmlTests/*.qml
%{_datadir}/tst-harbour-log4qtdemo-qmlTests/*.sh
# >> files test
# << files test
