#ifndef LOG4QTDEMOENGINE_H
#define LOG4QTDEMOENGINE_H

#include <QtCore/QtGlobal>

#if defined(LOG4QTDEMOENGINE_LIBRARY)
#  define LOG4QTDEMOENGINE_EXPORT Q_DECL_EXPORT
#else
#  define LOG4QTDEMOENGINE_EXPORT Q_DECL_IMPORT
#endif


void initLogging();

#endif // LOG4QTDEMOENGINE_H
